#include<stdio.h>

main()
{
    int y,m,d,n,a[13]={0,31,28,31,30,31,30,31,31,30,31,30,31},r;
    while(scanf("%d%d%d%d",&y,&m,&d,&n)!=EOF)
    {
        while(n>0)
        {
            if((y%400==0)||(y%100!=0&&y%4==0))
            {
                r=1;
            }
            else
            {
                r=0;
            }
            if(m==2)
            {
                if(d+n<=a[m]+r)
                {
                    d+=n,n=0;
                }
                else
                {
                    n-=a[m]-d+r+1,d=1,m++;
                }
                continue;
            }
            if(d+n<=a[m])
            {
                d+=n,n=0;
            }
            else
            {
                n-=a[m]-d+1,d=1,m++;
                if(m>12)
                {
                    m=1,y++;
                }
            }
        }
        printf("%d-%d-%d\n",y,m,d);
    }
    return 0;
}
